export const TASK_STATUS = {

    PENDING:"PENDING",

    IN_PROGRESS:"IN_PROGRESS",

    READY_FOR_REVIEW:"READY_FOR_REVIEW",

    APPROVED:"APPROVED",

    REJECTED:"REJECTED",

    COMPLETED:"COMPLETED"
};